# -*- coding: utf-8 -*-
"""Assignment1_Strings_Tuples

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h7s8E4XdmU-NU-swONzTQ1HKgVX7etUe
"""

name = input("Enter your Name: ")

str1 = "Hello "
str2 = name

result = str1 + str2
print(result)

str3 = ", welcome to Python programming"
result = result + str3
print(result)

text = "Hello Theia, welcome to Python programming"

print("Original String:", text)

# a. First character
print("a. First character:", text[0])

# b. Last character
print("b. Last character:", text[-1])

# c. First 5 characters
print("c. First 5 characters:", text[:5])

# d. Last 11 characters
print("d. Last 11 characters:", text[-11:])

# e. Reverse the string
print("e. Reverse:", text[::-1])

# f. Print the word 'Python'
start = text.find("Python")
print("f. Python:", text[start:start+6])

strM = "Python beginner tutorial"

# a. Convert to uppercase
print("Uppercase:", strM.upper())

# b. Convert to lowercase
print("Lowercase:", strM.lower())

# c. Capitalize
print("Capitalize:", strM.capitalize())

# d. Count occurrences of 't'
print("Count of 't':", strM.count('t'))

# e. Replace Python with Machine Learning
print("Replaced String:", strM.replace("Python", "Machine Learning"))

tuple1 = (10, 20, 30)
tuple2 = (40, 50, 60)

# a. Concatenate
t_combine = tuple1 + tuple2
print("Concatenated Tuple:", t_combine)

# b. Repeat 3 times
print("Repeated Tuple:", t_combine * 3)

# c. Third element
print("Third Element:", t_combine[2])

# d. First three elements
print("First Three Elements:", t_combine[:3])

# e. Last three elements
print("Last Three Elements:", t_combine[-3:])